draft-ietf-httpapi-ratelimit-headers.md

- uses http-core semantics #1 
- fixes Sections refs #4 
Fixes: #1 #4
cc: @reschke

Use http-core semantics, fix refs

---

draft-ietf-httpapi-ratelimit-headers.md

Improves terminology replacing `request-quota` with `service-limit`.
cc: @unleashed @bridgetlane #31

Fix: #31. Replace request-quota with service-limit.

---

draft-ietf-httpapi-ratelimit-headers.md

- specific throttling behavior is out of scope
- FAQ 8 integrated in RateLimit-Remaining and Receiving Ratelimit fields

Fix: #36. No specific throttling behavior.

---

draft-ietf-httpapi-ratelimit-headers.md

- servers are not forced to always return ratelimit fields
- clients must not assume the presence of ratelimit fields
- performance hints for providers

Fix: #27. Performance concerns on providing ratelimit headers

---

draft-ietf-httpapi-ratelimit-headers.md

Integrate @darrelmiller suggestions in the spec goal

Improve spec goal. See #26

---

draft-ietf-httpapi-ratelimit-headers.md

- MUST NOT expose unwanted throughput
- SHOULD cap conveyed throughput
- FAQ on `w` informative

Fix: #23. Cap conveyed throughput. See #19.

---

draft-ietf-httpapi-ratelimit-headers.md

- clarifies that status code is independent from the values of RL fields
- the example reflects the above statement.

Fix: #42 #44. Clarification on returning status codes.

---

draft-ietf-httpapi-ratelimit-headers.md

Improves example description
Fix: #37

Fix: #37. Improve "missing remaining information" example description

---

draft-ietf-httpapi-ratelimit-headers.md

note_to_readers: use the correct HTTP API WG mailing list archives link

---

draft-ietf-httpapi-ratelimit-headers.md

- uses structured fields
- based on @ucarion preliminary work: thanks!!!
- referencing the RFC
- distinguishing sf-item and sf-integer, since sf-integer do not support parameters whereas sf-item does 
- retaining the intermediate syntaxes (quota-policy, quota-units, service-limit, ...)

Fix: #6. Use Structured Fields.

---

draft-ietf-httpapi-ratelimit-headers.md

- consistent use of `fields` in document name
Fixes #68.
cc: @richsalz @darrelmiller

Fix: #68. Consistent use of FIELDS in document name.

---

draft-ietf-httpapi-ratelimit-headers.md

Clarifies that Without w a quota-policy is meaningless, so it's just a clarification.

quota-policy: `w` is REQUIRED

---

draft-ietf-httpapi-ratelimit-headers.md

- clarify that quota-policy examples are not field values.
Fix: #73

Fix: #73. Clarify quota policy examples.

---

draft-ietf-httpapi-ratelimit-headers.md

- a server SHOULD be configurable so that it can provide `Limit` with or without `quota-policy`
-  compliant clients have to use SFV parsers
- non-compliant / pre-existing clients can still process fields with quota-policy:off and be migrated in time.
eg..
```
RateLimit-Limit: 100
RateLimit-Remaining: 20
RateLimit-Reset: 12
```
```
RateLimit-Limit: 100,    100;w=20,    200;w=100
RateLimit-Remaining: 20
RateLimit-Reset: 12
```

Fix: #24. Migration strategy based on servers.

---

draft-ietf-httpapi-ratelimit-headers.md

- defers throttling scope to future implementations
- explains in FAQ why URL is the only interoperable choice.

Alternate throttling scope. Fix: #10

---

draft-ietf-httpapi-ratelimit-headers.md
test_ratelimit.py

- editorial references (SELF, HTTP, STRUCTURED-FIELDS)
- remove backticks
- remove ABNF

Preliminary editorial. See #89.

---

draft-ietf-httpapi-ratelimit-headers.md

According to https://www.rfc-editor.org/rfc/rfc8941.html#section-4.2-7
there is no need to specify that information. Fix: #94

Fix: #94. SF defines whether fields may appear one or more times.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #93 
- Parameters are not allowed, and if they appear they MUST be ignored.

Fix: #93. Tolerant reader.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #95. Remove traffic-light analogy.

---

draft-ietf-httpapi-ratelimit-headers.md

- clarify that we return only the values related to the quota policy identified by the expiring-limit 
Fix: #104

Fix: #104. Clarify we return the quota associated to expiring-limit

---

README.md

Update the link to the CONTRIBUTING.md not to point to the draft (which results in a 404 currently)

Fix the link to the CONTRIBUTING.md

---

draft-ietf-httpapi-ratelimit-headers.md

Is `r` mandatory? If so, it would be helpful to explicitly stat it so.

Require `r` parameter in RateLimit field

---

draft-ietf-httpapi-ratelimit-headers.md

The statement that the `RateLimit-Policy` header is not allowed in trailers is located in a section for examples of this field. This restriction better fits into the section that describes the header in the first place.

Move trailer restriction out of example section

---

draft-ietf-httpapi-ratelimit-headers.md

This unit is defined in https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-08.html#name-quota-unit-parameter but not mentioned in the unit registry.

Add missing quota unit to registry

---

draft-ietf-httpapi-ratelimit-headers.md

Feedback from IETF 121

---

draft-ietf-httpapi-ratelimit-headers.md

This pull request makes a series of editorial and clarification improvements to the `draft-ietf-httpapi-ratelimit-headers.md` document. The main focus is on updating references to RFCs, improving terminology consistency, clarifying normative requirements, and correcting minor typos and phrasing for better readability and accuracy.
Key changes include:
**Reference and Terminology Updates:**
* Updated references to RFC8941 (Structured Fields) and RFC6454 (Web Origin) throughout the document to use consistent shorthand (`SF` and `WEB-ORIGIN`) and improved how these are cited in the text. [[1]](diffhunk://#diff-d26a6f407efe0e4913cbcf7bf0e2a164bee5edea8bf2fdc4aa97a7ceb3acc03cR48-R49) [[2]](diffhunk://#diff-d26a6f407efe0e4913cbcf7bf0e2a164bee5edea8bf2fdc4aa97a7ceb3acc03cL93-R109) …

fix: Editorial issues
