ietf-wg-httpapi/ratelimit-headers

Makefile
README.md
draft-ietf-httpapi-ratelimit-headers.md

- adds new draft
- add Makefile

Add httpapi branch.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix examples (Host header, http-messages, ..)

---

README.md

Reference gh-pages

---

docker-compose.yml

Adds a docker-compose to run local tests on the I-D.

Add docker-compose to test locally

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #3. s,client application,user agent.

---

draft-ietf-httpapi-ratelimit-headers.md

- uses field instead of header
- fix normative references

Editorial improvements

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #38. FAQ about pinning status codes.

---

draft-ietf-httpapi-ratelimit-headers.md

- clarifies interaxtions with 3xx

Fix: #41. Clarify interactions with 3xx.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #50. Reformat goals.

---

draft-ietf-httpapi-ratelimit-headers.md

Reorganizes the document.
See #64

Reorganize document

---

draft-ietf-httpapi-ratelimit-headers.md

Update changelog
cc: @unleashed pls merge if you agree

Update changelog. See #66.

---

draft-ietf-httpapi-ratelimit-headers.md

- FAQ and Acks unnumbered
- FAQ to be removed before publication.
See #71 
@reschke PTAL :)

Fix: #71. Acks and FAQ unnumbered.

---

draft-ietf-httpapi-ratelimit-headers.md

- clarify fields dependencies according to the discussion in the issue
- fixes #11

Fix: #11. Clarify fields dependencies.

---

draft-ietf-httpapi-ratelimit-headers.md

Privacy considerations

---

draft-ietf-httpapi-ratelimit-headers.md

The redhat.com email address is no longer valid, so update my contact information with another address.

Update my email address

---

draft-ietf-httpapi-ratelimit-headers.md
test_ratelimit.py

- moves quota-policies from RateLimit-Limit -> RateLimit-Policy
- requires WG discussion
- Fixes: #79

Fix: #79. ratelimit-policy Proposal.

---

draft-ietf-httpapi-ratelimit-headers.md

Bump http to RFC9110

---

draft-ietf-httpapi-ratelimit-headers.md

I believe these are all editorial.

Editorial suggestions

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #98. SHOULD ignore cached fields.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: 103. No x- prefix

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #97. Ignore malformed fields.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #102. Reference RFC6973 for re-identification and correlation.

---

draft-ietf-httpapi-ratelimit-headers.md

See https://github.com/httpwg/http-extensions/commit/85c26b8acdd60a188ffa5752877cc4bff82c604a

Use venue.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #92. Rework concepts

---

draft-ietf-httpapi-ratelimit-headers.md

- no normative language in sec-
- Fix: #99 
- Fix: #96

Fix: #99, #96. No normative language in sec- + Validation

---

draft-ietf-httpapi-ratelimit-headers.md

- no trailers, but no normative language
- add explanation in FAQ, noting that it could be addressed in future specifications

Fix: #105. No trailers.

---

draft-ietf-httpapi-ratelimit-headers.md

- Fix #121
- clarify that quota policies are unique in policy.

Quota policies MUST be unique in Policy. See #121.

---

draft-ietf-httpapi-ratelimit-headers.md

- @darrelmiller suggestion on server behavior. Thx!
- Fixes: #120

Fix: #120. Clarification on requirements for server behavior.

---

draft-ietf-httpapi-ratelimit-headers.md

Fix: #64. Combine headers.
